name: lint

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: check-code-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.3
          cache: 'poetry'
      - run: poetry check
      - run: poetry install
      - run: poetry run flake8 --config=./.flake8 .
      - run: poetry run mypy --config-file=pyproject.toml .
      - run: poetry run black --check .
      - run: poetry run isort --check .
